#!/bin/bash


set -exo pipefail

repos=("https://github.com/openshift/alibaba-disk-csi-driver-operator"\
	   "https://github.com/openshift/aws-ebs-csi-driver-operator"\
	   "https://github.com/openshift/aws-efs-csi-driver-operator"\
	   "https://github.com/openshift/azure-disk-csi-driver-operator"\
	   "https://github.com/openshift/azure-file-csi-driver-operator"\
	   "https://github.com/openshift/cluster-storage-operator"\
	   "https://github.com/openshift/csi-driver-manila-operator"\
	   "https://github.com/openshift/gcp-filestore-csi-driver"\
	   "https://github.com/openshift/gcp-pd-csi-driver-operator"\
	   "https://github.com/openshift/ibm-vpc-block-csi-driver-operator"\
	   "https://github.com/openshift/openstack-cinder-csi-driver-operator"\
	   "https://github.com/openshift/secrets-store-csi-driver-operator"\
	   "https://github.com/openshift/vmware-vsphere-csi-driver-operator"\
	   "https://github.com/openshift/cluster-csi-snapshot-controller-operator")

for repo in "${repos[@]}"; do
    echo "Patching $repo..."
    
    dir=$(basename "$repo")

    # Create directory for the repo
    mkdir -p "$dir"
    pushd "$dir" || exit

    # Clone openshift repository
    gh repo clone "$repo" .
    git remote rename origin openshift
    gh repo set-default "openshift/$dir"

    # Create a fork, if one doesn't exist yet
    gh repo fork --remote
    default_branch="master"
    if git show-ref --verify --quiet refs/heads/main; then
	default_branch="main"
    fi

    # Create a custom branch
    git checkout -B bump-x-net "openshift/$default_branch"

    # Update go dependency
    go get golang.org/x/net@v0.17.0
    go mod tidy
    go mod vendor

    # If git status reports any changes, add everything to the index, push and create a PR
    status=$(git status --porcelain)
    if [ -n "$status" ]; then
	git add .
	git commit -m 'UPSTREAM: <carry>: bump golang.org/x/net to v0.17.0'
	git push origin -u HEAD -f
	gh pr create --title "Bump golang.org/x/net to v0.27.0" --body "Auto-generated by https://github.com/bertinatto/bummer." -w || true
    fi

    # Return to previous directory
    popd || exit

done
